/** Couple-oriented questions for the "who is more likely" game. */
export const MOST_LIKELY_QUESTIONS: readonly string[] = [
  '¿Quién es más probable que proponga un plan improvisado a medianoche?',
  '¿Quién es más probable que se ponga celoso primero?',
  '¿Quién es más probable que diga "te amo" dormido?',
  '¿Quién es más probable que olvide el aniversario?',
  '¿Quién es más probable que mande un mensaje atrevido en horario laboral?',
  '¿Quién es más probable que quiera repetir esta noche?',
  '¿Quién es más probable que se ría en el peor momento?',
  '¿Quién es más probable que inicie un beso en público?',
  '¿Quién es más probable que stalkee al otro en redes?',
  '¿Quién es más probable que planee una escapada sorpresa?',
  '¿Quién es más probable que se quede dormido después?',
  '¿Quién es más probable que pida jugar a este juego otra vez?',
  '¿Quién es más probable que rompa una regla de la casa?',
  '¿Quién es más probable que proponga probar algo nuevo en la cama?',
  '¿Quién es más probable que se sonroje con una pregunta de este juego?',
  '¿Quién es más probable que gaste de más en un regalo?',
  '¿Quién es más probable que cancele planes para quedarse en casa juntos?',
  '¿Quién es más probable que le cuente todo a sus amigos?',
  '¿Quién es más probable que empiece una pelea de cosquillas?',
  '¿Quién es más probable que use la ropa del otro?',
  '¿Quién es más probable que cocine algo especial para seducir?',
  '¿Quién es más probable que sugiera bañarse juntos?',
  '¿Quién es más probable que pierda una apuesta entre ustedes?',
  '¿Quién es más probable que se despierte con ganas a las 3 AM?',
  '¿Quién es más probable que grabe una nota de voz cantando?',
  '¿Quién es más probable que diga un piropo malísimo con orgullo?',
  '¿Quién es más probable que se olvide de responder un mensaje del otro?',
  '¿Quién es más probable que quiera bailar pegados sin música?',
  '¿Quién es más probable que esconda un regalo y lo olvide?',
  '¿Quién es más probable que proponga la próxima pose de la colección?',
  '¿Quién es más probable que se ponga romántico después de dos tragos?',
  '¿Quién es más probable que quiera fotos de todo?',
  '¿Quién es más probable que hable dormido y diga algo comprometedor?',
  '¿Quién es más probable que gane si esto fuera una competencia?',
  '¿Quién es más probable que llore en una película romántica?',
  '¿Quién es más probable que sugiera apagar los teléfonos esta noche?',
]
